cmake_minimum_required(VERSION 3.26)

add_subdirectory(core)
add_subdirectory(widgets)
add_subdirectory(ems_save)
if(NOT SNF_WEB_ASSEMBLY)
    if(SNF_ENABLE_SNMP)
    add_subdirectory(snmp_read_write)
    add_subdirectory(snmp_trap_concurrent)
    add_subdirectory(snmp_server_client)
    endif()
    if(SNF_ENABLE_SNMP_SERVER)
    add_subdirectory(snmp_server)
    endif()
endif()